### ISSUE TITLE
List comprehension

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/version_2_exercises_for_programmers#16]
I'm trying to convert the code below from a for loop to a list comprehension:

```
x = [1, 2, 3, 4, -5, -6]

new_numbers = []

for number in x:
    if number < 0:
        del number
    else:
        new_numbers.append(number)

print(new_numbers)

```

The for loop above works, but I can't get the list comprehension to work, and I've tried many variations. Here are two:

```
new_numbers = [if number >0 else del number for number in x ] 
print(new_numbers)
```
```

new_numbers = [for number in x if number <0: del number]
print(new_numbers)

```

I realize that the formula for list comprehensions is: 
variable_name = [expression for variable in iterable if_condition]

But I'm not sure how this works when the 2nd line of the for loop (above) is an if-statement?

**Comment by paulghaddad** [comment]
@amymhaddad 

This is what you'll want to do. Instead of _deleting_ a number that doesn't match the criteria, you can just build up a new list with the numbers that are `>= 0`:

```
x = [1, 2, 3, 4, -5, -6]

new_numbers = [num for num in x if num >= 0
```

This should give back `[1, 2, 3, 4]`. Another approach is to use the `filter` method. But what both are doing is not worrying about the original list, `x`, but focusing on building up a _new_ list with the numbers you want.

**Comment by amymhaddad** [comment]
@paulghaddad The list comprehension makes sense! What would the filter option look like? I took a stab at it but am getting an error:

x = [1, 2, 3, 4, -5, -6]
filtered_numbers = list(filter(lambda number: number for number in x if number <= 0, x))

**Comment by paulghaddad** [comment]
I think filter will be something like:

```
filtered_numbers = list(filter(lambda number: number <= 0, x))
```

Remember with `filter`, you're applying the lambda function to a _single_ item in the list, so just `number <= 0`.
